### ISSUE TITLE
Yahoo/Oath codes

### ISSUE THREAD

**Issue by nirebu** [wildbit/smtp-field-manual#2]
Hello,
I don't see any Yahoo specific return code. Is there a reason they're left out? If it were possible, I'd like to contribute with some of those.

**Comment by derekrushforth** [comment]
Awesome! No reason in particular why we left Yahoo out. We'd love to provide their responses though. Feel free to contribute!

- Add Yahoo to the [provider list](https://github.com/wildbit/smtp-field-manual/blob/master/data/EmailProviders.json)
- Add the responses to the [corresponding code](https://github.com/wildbit/smtp-field-manual/tree/master/data/codes) under the [`providers`](https://github.com/wildbit/smtp-field-manual/blob/master/data/codes/422.json#L5) field

You can always leave the responses here and I can add them in too.

**Comment by nirebu** [comment]
Cool! I'll collect them and make sure to open a PR for them as soon as I can.

**Comment by derekrushforth** [comment]
Hey @nirebu, someone from our team contributed some Yahoo responses today. https://smtpfieldmanual.com/provider/yahoo

You'll want to pull from the upstream master branch before adding your responses. Just FYI.

**Comment by nirebu** [comment]
I've been too slow 😊 the seven codes I was about to add have already been added.

**Comment by derekrushforth** [comment]
@nirebu Aw, darn! No worries :)
