### ISSUE TITLE
Merging Hotmail and Outlook providers

### ISSUE THREAD

**Issue by nirebu** [wildbit/smtp-field-manual#23]
I wanted to open a discussion on whether it should be a good idea to merge the above mentioned providers and related response codes. Am I mistaken in thinking that they are the same and behave the same once you hit their servers?

**Comment by howdyanna** [comment]
This makes sense to me. We merged Yahoo and AOL into "Verizon", so following that convention we could do the same with Outlook and Hotmail.

**Comment by nirebu** [comment]
If that's OK, I can do that and submit a PR.

**Comment by derekrushforth** [comment]
@nirebu I'm good with this. We should also add a list of recipient domains that each provider owns as well. Feel free to merge the providers and I'll submit a follow-up PR.

**Comment by nirebu** [comment]
Closing this issue because b2e504d addresses this and much more.
