### ISSUE TITLE
Search may not correctly query all responses

### ISSUE THREAD

**Issue by mrosata** [wildbit/smtp-field-manual#29]
Searching from the main page for either `5.4.1`, `550 5.4.1` or `smtp;550 5.4.1` doesn't return any results

I would expect it to match responses such as this one in ./data/codes/550.json:
https://github.com/wildbit/smtp-field-manual/blob/c59e44ed3e638a5f707cb9b942ea09bfc126696a/data/codes/550.json#L225-L228

**Comment by derekrushforth** [comment]
Turns out we weren't uploading any of the responses from spam filter services to Algolia. Only email providers. It's fixed now. Thanks for catching this!

**Comment by mrosata** [comment]
No prob, and thank you as well 😄
