### ISSUE TITLE
simple advice

### ISSUE THREAD

**Issue by henzeb** [wildbit/smtp-field-manual#42]
Most providers send out the description of the errorcode in their response. So if you have a manual, please add some info on how to fix this issue... 

for instance
smtp;450 4.7.3 Organization queue quota exceeded. [outlook.com]

this error is exactly what I got as response. but the response or the manual does not state how to fix this. would be nice and actually helpful if anything like that was added...

**Comment by fm** [comment]
This aligns with #27. I'd be happy to work on it, but we'd need to see with @derekrushforth on how it would be implemented

**Comment by briankerr** [comment]
@henzeb @fm This is great thinking! And I have good news. To start off the year, we're working on a refresh of the SMTP Field Manual. The biggest change you'll notice is is we now list the cause and resolution suggestions for bounces!

For the mentioned bounce, you can see that here: https://smtpfieldmanual.com/provider/outlook/450/4.7.3.

We've also added a bunch more bounces, more email providers/email filters, and added a label for how severe the bounce is. 

All open source, so if someone has tips or more bounces to add they can [fork and submit a PR](https://smtpfieldmanual.com/contribute) 😄
